### ISSUE TITLE
Add additional maintainers

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/looptools-feedstock#1]
> Just a heads up that the hash sum of the latest (2.16) version keeps changing with every update.
> ...
> That's why gentoo only has 2.15 https://packages.gentoo.org/packages/sci-physics/looptools.

_Originally posted by @APN-Pucky in https://github.com/conda-forge/staged-recipes/pull/28292#issuecomment-2496222882_

@APN-Pucky, as you're also a package maintainer of LoopTools for Gentoo, would you like to be added as a feedstock maintainer?

**Comment by APN-Pucky** [comment]
I do not use conda and currently my priorities for hep codes are in order:
1. Gentoo
2. EasyBuild
3. EESSI

and since it is not part of my "work" but for fun I don't have time for more, but I'd like to help by reviewing/commenting/answering questions.
Maybe one could think of some sort of organization that coordinates/communicates between all the efforts.   I list a few below.
 For some projects it is difficult as a single person to push changes to upstream, but maybe together?

I am aware of (https://repology.org/project/lhapdf/versions and more):
- Gentoo: 
  - https://github.com/gentoo/gentoo/tree/master/sci-physics 
  - https://github.com/gentoo/sci/tree/master/sci-physics
  - my experimental repo for gentoo https://gitlab.com/APN-Pucky/gentoo-hep-forge/-/tree/master/sci-physics?ref_type=heads
- conda https://github.com/hep-packaging-coordination
- https://github.com/wavewave/hep-nix-overlay/tree/master/pkgs
- https://packages.spack.io/package.html?name=lhapdf (see required by)
- https://docs.easybuild.io/version-specific/supported-software/l/LHAPDF/
- https://www.eessi.io/docs/available_software/detail/LHAPDF/
- https://github.com/andriish/HEPrpms
- https://archlinux.org/packages/extra/x86_64/lhapdf/
- https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/physics (more in other categories), https://repology.org/projects/?maintainer=veprbl@gmail.com&inrepo=nix_unstable&newest=1
- CERN/CVMFS SFT/LCG https://ep-dep-sft.web.cern.ch/document/lcg-releases

In some cases the repos are not sorted so I just pick an example.

**Comment by matthewfeickert** [comment]
> since it is not part of my "work" but for fun I don't have time for more, but I'd like to help by reviewing/commenting/answering questions.

Thanks @APN-Pucky and sounds good. 👍 I'll close this as the original issue point is resolved, but we can continue talking here.

> currently my priorities for hep codes are in order:
>
> 1. Gentoo
> 2. EasyBuild
> 3. EESSI

I'm not asking for reasons unrelated to this issue and mostly just out of pure curiosity, but can you tell me a bit about how the HEP theory/phenomenology community uses these? Is Gentoo a common distro that people have standardized around? I don't have experience with [EasyBuild](https://docs.easybuild.io/) and I guess EESSI is https://github.com/EESSI(?). It seems that both are focused on HPCs specifically. I assume this isn't about compiler optimisation but about automating HPC specific builds as all HPCs have their own oddities? 

> Maybe one could think of some sort of organization that coordinates/communicates between all the efforts

Maybe. I think it would help to understand why each exists in the first place.

The reason that I'm drawn to using conda-forge for packaging and distribution is that it offers multi-platform support and so you don't have to resolve packaging for each Linux distribution. I appreciate that Nix addresses this too, but there doesn't seem to be widespread use of Nix anywhere in HEP at the moment (the repo you link to is even archived). I also realistically don't know enough about the subtleties of HPC computing to be able to offer much insight here, as most of my "HPC" work is on GPUs and I tend to work on HTC systems more. CVMFS / LCG views are very useful for C++, but you're still stuck with whatever is already available for you &mdash; you can't do your own project packaging in a reasonable way.

**Comment by matthewfeickert** [comment]
> I also realistically don't know enough about the subtleties of HPC computing to be able to offer much insight here, as most of my "HPC" work is on GPUs and I tend to work on HTC systems more. 

@kratsg you've recently done some HPC Fortran work for an ATLAS analysis. How were you setting up your software environment there?

**Comment by APN-Pucky** [comment]
EasyBuild is like spack a (source) package manager targeted at HPCs. That is they install into directories that can be loaded/activated as modules (probably similar to conda). Each HPC provides the software then compiled specifically for their hardware.

The colloquial EESSI slogan is "streaming scientific software". EESSI uses EasyBuild to generate again loadable modules, but the idea is that the software stack is shared across multiple HPC (currently each HPC maintains their own). The sharing is done over CVMFS and will pick the right optimized-compiled software for your hardware. I can also load the same modules on my PC/Laptop, therefore use the same environment developing locally and doing long runs on the cluster. Advanced usage then is that it also works in a CI on github (to get the dependencies for a project) and with `direnv` you can switch your env in seconds between project folders. More documentation is here: https://www.eessi.io/docs/overview/
Example (for common cern machine or lxplus or anything with cvmfs (afaik incl. macos excl. windows)):
```bash
apn@APNsL13 /cvmfs $ source /cvmfs/software.eessi.io/versions/2023.06/init/lmod/bash
bash: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/share/Lmod/init/bash: Input/output error
EESSI/2023.06 loaded successfully
apn@APNsL13 /cvmfs $ command -v rivet
/usr/bin/rivet
apn@APNsL13 /cvmfs $ module load Rivet
To use your own analysis you must append the path to `RIVET_ANALYSIS_PATH`.
You might want to load `texlive` or `matplotlib` if you want to create plots.
apn@APNsL13 /cvmfs $ command -v rivet
/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen3/software/Rivet/3.1.9-gompi-2023a-HepMC3-3.2.6/bin/rivet
```
You see my laptop uses the zen3 compiler stack. Initial cvmfs commands take a bit to fetch the data, but then it is cached locally.


I don't think many individuals use Gentoo, but EESSI and some CVMFS software use it, though not the HEP specific codes, but the more fundamental machinery. For me it is just nice to control everything (running stuff with debug flags/profiler, switching versions, etc.). I also catch bugs early with Gentoo tests/QA (it is a [Chaos Monkey](https://en.wikipedia.org/wiki/Chaos_engineering), installing random packages until sth. goes wrong) and can report/try-to-fix them.

**Comment by APN-Pucky** [comment]
I forgot to mention that the Gentoo stuff is also available directly on CVMFS through gentoo prefix (sort of like unprivileged chroot):
```
apn@APNsL13 /cvmfs $ /cvmfs/sft.cern.ch/lcg/contrib/gentoo/linux/x86_64/startprefix
Entering Gentoo Prefix /cvmfs/sft.cern.ch/lcg/contrib/gentoo/linux/x86_64
APNsL13 /cvmfs $ command -v root
/cvmfs/sft.cern.ch/lcg/contrib/gentoo/linux/x86_64/usr/lib/root/6.24/bin/root
```
In principle the other HEP codes I maintain could also be installed there, but atm it is just exp codes like root/geant/etc (`ls /cvmfs/sft.cern.ch/lcg/contrib/gentoo/linux/x86_64/var/db/pkg/sci-physics`).

**Comment by kratsg** [comment]
Yeah, for HPCs, a lot of what I did was on Perlmutter lately - but we found EasyBuild a bit harder to use there for some reason (I'm not quite sure why but I suspect it had to do with it being Fortran + requiring the dedicated mpi compilers for the HPCs there and those are custom built for the architecture). For at least the few fortran libs I was using, those were driven through `cmake` purely and never had a particular issue as long as one used the dedicated compilers provided by the HPC.
